apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- literals:
  - bucket=dev
  - roleARN=dev
  - table-name=dev
  - db-connection-secret=db-connection-dev
  name: dev-config
  options:
    disableNameSuffixHash: true
    labels:
      workflows.argoproj.io/configmap-type: Parameter

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_workflows_kustomize_schema.json

patchesStrategicMerge:
- argument-patch.yaml

images:
- name: count
  newName: ghcr.io/nikita-akuity/count
  newTag: sha-5a0f611
- name: greetings
  newName: ghcr.io/nikita-akuity/greetings
  newTag: sha-5a0f611
- name: replace-text
  newName: ghcr.io/nikita-akuity/replace-text
  newTag: sha-5a0f611
